- name: Set up environment variables
      env:
        ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_ORG_ID }}
        ANYPOINT_ENV_ID: ${{ secrets.ANYPOINT_ENV_ID }}
        ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
        ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}

    - name: Get MuleSoft Access Token
      id: get_token
      run: |
        TOKEN_RESPONSE=$(curl -s --location --request POST 'https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token' \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --data-urlencode "client_id=${{ secrets.ANYPOINT_CLIENT_ID }}" \
        --data-urlencode "client_secret=${{ secrets.ANYPOINT_CLIENT_SECRET }}" \
        --data-urlencode 'grant_type=client_credentials')
        TOKEN=$(echo $TOKEN_RESPONSE | jq -r .access_token)
        echo "::set-output name=token::$TOKEN"

    - name: Upload Custom Policy
      run: |
        curl --location --request POST "https://anypoint.mulesoft.com/apimanager/api/v1/organizations/${{ secrets.ANYPOINT_ORG_ID }}/environments/${{ secrets.ANYPOINT_ENV_ID }}/exchange-policy-templates" \
        --header "Authorization: Bearer ${{ steps.get_token.outputs.token }}" \
        --header 'Content-Type: application/json' \
        --data-binary "@/path/to/your/policy.zip"
