- name: Set up environment variables
      env:
        ANYPOINT_ORG_ID: ${{ secrets.ANYPOINT_ORG_ID }}
        ANYPOINT_ENV_ID: ${{ secrets.ANYPOINT_ENV_ID }}
        ANYPOINT_CLIENT_ID: ${{ secrets.ANYPOINT_CLIENT_ID }}
        ANYPOINT_CLIENT_SECRET: ${{ secrets.ANYPOINT_CLIENT_SECRET }}

    - name: Retrieve Anypoint Access Token
        id: get-token
        run: |
          response=$(curl -X POST \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials&client_id=${{ secrets.ANYPOINT_CLIENT_ID }}&client_secret=${{ secrets.ANYPOINT_CLIENT_SECRET }}" \
            "https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token")
          echo "access_token=$(echo $response | jq -r '.access_token')" >> response_body
    - name: Upload Custom Policy
      run: |
        curl --location --request POST "https://anypoint.mulesoft.com/apimanager/api/v1/organizations/${{ secrets.ANYPOINT_ORG_ID }}/environments/${{ secrets.ANYPOINT_ENV_ID }}/exchange-policy-templates" \
        --header "Authorization: Bearer ${{ steps.get_token.outputs.token }}" \
        --header 'Content-Type: application/json' \
        --data-binary "@/path/to/your/policy.zip"
